apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roip-lakehouse-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.bronzeSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roip-checkpoint-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: "5Gi"