USE DATABASE ROIP_DB;
USE SCHEMA GOLD;

-- ── Daily revenue summary ─────────────────────────────────────────────
CREATE OR REPLACE VIEW V_DAILY_REVENUE AS
SELECT
    EVENT_DATE,
    SUM(ORDER_COUNT)      AS TOTAL_ORDERS,
    SUM(GROSS_REVENUE)    AS TOTAL_REVENUE,
    AVG(AVG_ORDER_VALUE)  AS AVG_ORDER_VALUE,
    SUM(UNIQUE_CUSTOMERS) AS UNIQUE_CUSTOMERS
FROM FACT_HOURLY_ORDERS
GROUP BY EVENT_DATE
ORDER BY EVENT_DATE DESC;

-- ── City performance leaderboard ──────────────────────────────────────
CREATE OR REPLACE VIEW V_CITY_LEADERBOARD AS
SELECT
    EVENT_DATE,
    CITY,
    SUM(ORDER_COUNT)   AS TOTAL_ORDERS,
    SUM(GROSS_REVENUE) AS TOTAL_REVENUE,
    RANK() OVER (
        PARTITION BY EVENT_DATE
        ORDER BY SUM(GROSS_REVENUE) DESC
    )                  AS REVENUE_RANK
FROM FACT_HOURLY_ORDERS
GROUP BY EVENT_DATE, CITY;

-- ── SLA compliance rate by city ───────────────────────────────────────
CREATE OR REPLACE VIEW V_SLA_COMPLIANCE AS
SELECT
    EVENT_DATE,
    CITY,
    SUM(CASE WHEN DELIVERY_STATUS = 'ON_TIME' THEN ORDER_COUNT ELSE 0 END)
        AS ON_TIME_ORDERS,
    SUM(ORDER_COUNT) AS TOTAL_ORDERS,
    ROUND(
        100.0 * SUM(CASE WHEN DELIVERY_STATUS = 'ON_TIME'
                    THEN ORDER_COUNT ELSE 0 END) /
        NULLIF(SUM(ORDER_COUNT), 0),
        2
    ) AS SLA_COMPLIANCE_PCT
FROM FACT_DAILY_SLA
GROUP BY EVENT_DATE, CITY
ORDER BY EVENT_DATE DESC, SLA_COMPLIANCE_PCT ASC;

-- ── Payment failure rate ──────────────────────────────────────────────
CREATE OR REPLACE VIEW V_PAYMENT_HEALTH AS
SELECT
    EVENT_DATE,
    SUM(CASE WHEN EVENT_TYPE = 'PAYMENT_SUCCESS' THEN EVENT_COUNT ELSE 0 END)
        AS SUCCESSFUL_PAYMENTS,
    SUM(CASE WHEN EVENT_TYPE = 'PAYMENT_FAILED'  THEN EVENT_COUNT ELSE 0 END)
        AS FAILED_PAYMENTS,
    ROUND(
        100.0 * SUM(CASE WHEN EVENT_TYPE = 'PAYMENT_FAILED'
                    THEN EVENT_COUNT ELSE 0 END) /
        NULLIF(SUM(EVENT_COUNT), 0),
        2
    ) AS FAILURE_RATE_PCT
FROM FACT_PAYMENT_HEALTH
GROUP BY EVENT_DATE
ORDER BY EVENT_DATE DESC;

-- ── Hourly ops dashboard (real-time feel) ─────────────────────────────
CREATE OR REPLACE VIEW V_TODAY_HOURLY AS
SELECT
    EVENT_HOUR,
    CITY,
    CATEGORY,
    ORDER_COUNT,
    GROSS_REVENUE,
    AVG_ORDER_VALUE
FROM FACT_HOURLY_ORDERS
WHERE EVENT_DATE = CURRENT_DATE()
ORDER BY EVENT_HOUR DESC, GROSS_REVENUE DESC;