apiVersion: v1
kind: Secret
metadata:
  name: roip-secrets
  namespace: roip
type: Opaque
stringData:
  kafka-bootstrap-servers: "kafka-service:9092"
  snowflake-account:        "your_account.snowflakecomputing.com"
  snowflake-user:           "roip_loader"
  snowflake-password:       "CHANGE_ME"
  snowflake-database:       "ROIP_DB"
  snowflake-schema:         "GOLD"
  snowflake-warehouse:      "ROIP_WH"